schema: ip_object.v1
id: cortex_m7_systick
name: cortex_m7_systick
owner: happygrowth33
status: draft
created_at: 2026-06-23T13:47:41Z
stages:
  - req
  - rtl
  - tb
  - sim
  - lint
  - cov
  - formal
  - syn
  - signoff
